language: node_js
node_js: stable
branches:
  only:
  - source
cache:
  # apt: true
  # yarn: true
  directories:
  # - node_modules
before_install:
- openssl aes-256-cbc -K $encrypted_9b2d7e19d83c_key -iv $encrypted_9b2d7e19d83c_iv
  -in id_rsa.enc -out ~/.ssh/id_rsa -d
- chmod 600 ~/.ssh/id_rsa
- echo -e "Host 主机IP地址\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
- git config --global user.name "wsw"
- git config --global user.email "wswei99@126.com"
# - curl -o- -L https://yarnpkg.com/install.sh | bash
# - export PATH=$HOME/.yarn/bin:$PATH
# - npm install -g hexo-cli
install:
# - yarn
script:
# - hexo clean
# - hexo generate
after_success:
- rsync -rv --delete -e 'ssh -o stricthostkeychecking=no' public/ root@118.190.244.87:/usr/share/nginx/html
- cd ./public
- git init
- git add --all .
- git commit -m "Travis CI Auto Builder"
- git push --quiet --force https://$REPO_TOKEN@github.com/wswei99/wswei99.github.io.git
  master
